name: Lint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          - '3.7'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: >-
          cd .. && git clone https://github.com/haikuports/haikuporter.git --depth=1 && cd haikuports
      - run: 'PATH=$PATH:../haikuporter && export PATH'
      - run: >-
          printf 'TREE_PATH="'`pwd`'"\nPACKAGER="Nobody <server@fake>"\nTARGET_ARCHITECTURE="x86"\n' >haikuports.conf
      - run: >-
          wget https://github.com/waddlesplash/haiku-licenses/archive/master.zip
          && unzip master.zip
      - run: >-
          ./lint-new-recipes.sh --config=haikuports.conf
          --licenses=haiku-licenses-master
